name: JS CI

on:
  pull_request:
    branches:
      - development
    paths:
      - '**/*.js'

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.2

      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install # will run `yarn install` command
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build bundle
        working-directory: client
        uses: borales/actions-yarn@v4
        with:
          cmd: build:prod
      - name: Test the app
        working-directory: client
        uses: borales/actions-yarn@v4
        with:
          cmd: test
