name: Run mypy

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-build.txt
    - name: Run mypy
      working-directory: api
      run: mypy .
